services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.5
    container_name: hotel-keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=${DB_USERNAME:-admin}
      - KC_DB_PASSWORD=${DB_PASSWORD:-admin}
      - KC_HTTP_ENABLED=true
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/keyclaok-import/realm-config.json:/opt/keycloak/data/import/realm-config.json
    command: start-dev --import-realm --features=token-exchange
    depends_on:
      - postgres
    networks:
      - restaurant-network
  postgres:
    image: postgres:16
    container_name: restaurant-postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=${DB_USERNAME:-admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-admin}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - restaurant-network
networks:
  restaurant-network:
    driver: bridge
volumes:
  postgres_data: {}